language: python
dist: xenial
sudo: false

matrix:
  include:
  - python: 2.7
    env: TOX_ENV=py27
  - python: 3.5
    env: TOX_ENV=py35
  - python: 3.6
    env: TOX_ENV=py36
  - python: 3.6
    env: TOX_ENV=flake8
  - python: 3.6
    env: TOX_ENV=coveralls

install: pip install tox

script: tox -e $TOX_ENV
