language: python
dist: xenial
sudo: false

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
  - python: 3.6
    env: TOXENV=flake8
  - python: 3.6
    env: TOXENV=codecov
  - python: 3.6
    env: TOXENV=coveralls
  allow_failures:
  - python: 3.8-dev
    env: TOXENV=py38dev

install: pip install tox

script: tox
